### ISSUE TITLE
Makes sense to rebuild the site during the night?

### ISSUE THREAD

**Issue by hell03610** [VLCTechHub/VLCTechHub-site#110]
We are rebuilding the website every 15 minutes:
https://github.com/VLCTechHub/VLCTechHub-site/blob/39283ec07e2eb954f6c6db294a452e8e3391b7fe/.github/workflows/site-refresh.yml#L5

But does it make sense to build it even during the night? Could we say we want to **rebuild it from 7am to 11pm**? Would that be enough? What do you think @esebastian ?

See [examples of crons](https://stackoverflow.com/questions/41743720/crontab-run-every-15-minutes-between-certain-hours) runing between certain hours.

**Comment by esebastian** [comment]
I would say that it only makes sense to rebuild the site when there are pending changes. I guess we could do that by triggering the publishing workflow from the API when a new event or job offer is approved, throttling the triggering over specific periods of time (e.g. 15 min) to avoid continuous invocations.

In the meantime, we can update the schedule in almost every way we deem appropriate, as GitHub Actions uses `cron` syntax for that. The target audience for the site is mainly people around Valencia, so it would make sense to ignore different timezones and rebuild the site only from 7am to 11pm.
