### ISSUE TITLE
Community list

### ISSUE THREAD

**Issue by hell03610** [VLCTechHub/VLCTechHub-site#21]
Show a list of communities that have at least one event
In order to discover and give visibility to communities

Community list should show name, twitter avatar, twitter handler and twitter description for each twitter handler that we have.

**Comment by esebastian** [comment]
Should this come from the backend or are you planning process the data in the client?

**Comment by hell03610** [comment]
Backend as well, new endpoint and aggregated data possibly in separated
collection. I wanted to write here to do a spike on the fronted.

**Comment by hell03610** [comment]
Closing this as I think we will static data from https://trello.com/c/OnoWFnzw/101-comunidades-y-contactos or from https://comunidad-tecnologica.github.io/valencia/
