### ISSUE TITLE
Tweet the job 

### ISSUE THREAD

**Issue by hell03610** [VLCTechHub/VLCTechHub-site#30]
Being able to tweet each of the the jobs, with a twitter button
Tweet should say: 
- Job title
- Link to offer
- via @VLCTechHub

Question: Should we link to the current offer or to some "permalink"?

**Comment by hell03610** [comment]
Other option is to use twitter cards: https://dev.twitter.com/cards/overview

**Comment by esebastian** [comment]
In the majority of platforms links usually expire when the position is closed, but it could be interesting to keep them accessible, as an archive of sorts.

**Comment by esebastian** [comment]
Twitter cards are permanent?

**Comment by hell03610** [comment]
What do you mean by permanent?

Problem with meta attrs, not all scrappers are js friendly.
It could be the case where twitter could not read meta attrs generated by js.
I have not tried it...

**Comment by esebastian** [comment]
By permanent I mean: does the card still shows if the linked document no longer exists? Is it some sort of permalink in itself, like a tweet URL?

**Comment by hell03610** [comment]
http://blog.isnorcreative.com/2015/08/30/injecting-open-graph-tags-into-ember-for-facebook-sharing.html

**Comment by DavidHernandez** [comment]
Can this be closed? Job offers are already being tweeted: https://twitter.com/VLCTechHub/status/1157352217655087104

**Comment by hell03610** [comment]
yes, it'll be addressed in the new site
