### ISSUE TITLE
Do not have RSS for upcoming events

### ISSUE THREAD

**Issue by tanrax** [VLCTechHub/VLCTechHub-site#38]

**Comment by hell03610** [comment]
It's finally coming in the new version of the site! Closing this for now.

**Comment by hell03610** [comment]
Actually, I'll move it to the revamp backlog ;)

**Comment by hell03610** [comment]
RSS are available in the beta website at
vlctechhub-revamp.surge.sh/events/upcoming/feed.xml
vlctechhub-revamp.surge.sh/job/board/feed.xml

They will available at vlctechhub.org when we publish the new website
