### ISSUE TITLE
Add RSS icon to job board

### ISSUE THREAD

**Issue by hell03610** [VLCTechHub/VLCTechHub-site#56]
The job board page has a rss feed at `/job/board/feed.xml` but it is not currently displayed anywhere, so people wont know that option is available.

We would like to add an rss icon linked to the feed in the job board page.
We dont have any designs for that.

**Comment by jantznick** [comment]
#69 
Created a pull request for this, thanks!

**Comment by hell03610** [comment]
Closing this issue as the pull request was already merged! :tada: 

If you would like to autolink issues and pull request that can be done in the commit message, for example "Resolves vlctechhub/VLCTechHub-site#69 - Add rss icon to jobs" or with any other of the supported keywords (https://help.github.com/en/articles/closing-issues-using-keywords)
