### ISSUE TITLE
Add RSS icon to upcoming events

### ISSUE THREAD

**Issue by hell03610** [VLCTechHub/VLCTechHub-site#57]
The upcoming events  page has a rss feed at `/events/upcoming/feed.xml` but it is not currently displayed anywhere, so people wont know that option is available.

We would like to add an rss icon linked to the feed in the main page where the upcoming events are displayed. We dont have any designs for that.

**Comment by jantznick** [comment]
If anyone gets to this in the next day or two, I did add an RSS icon to the job board that is currently in PR, with some styling already created, so this could be pretty simple. If not I can probably do it later this week.

For @hell03610, would it make sense to also put the link in the footer with the social links?

**Comment by hell03610** [comment]
Thanks @jantznick! I'm already talking to the local community to promote this repo and get more hands on it - but feel free to contribute in any issue you like :D

I dont have a strong opinion about adding it to the footer, I can see pros and cons but I do think that we need to rethink the footer in the future to improve how to discover the info that is there (which is not very visible). Maybe one option will be to get rid of the whole footer and place the info more contextual and/or create content to discover and explain those hidden "functionalities" (for example, the slack and the browser extensions).

**Comment by hell03610** [comment]
Already shipped! :tada:
