### ISSUE TITLE
Add docker image

### ISSUE THREAD

**Issue by andoniaf** [VLCTechHub/VLCTechHub-site#74]
Setting up the project in my laptop I thought it was a good idea to create a docker container to make it easier for anyone who wants to contribute to run the project in their local environment.

Do you think it's a good idea?

**Comment by andoniaf** [comment]
I've created this #75 PR to add it.

Tomorrow I will add some info to the README and the "Construyendo el sitio web" section in CONTRIBUTING.md and remove the "draft" status form the PR.

**Comment by andoniaf** [comment]
I'm not sure about where I should add the info about how to run the site with docker. Inside "# 🚀 Construyendo el sitio web" or creating a section called "# 🚀 Construyendo el sitio web con Docker"?

**Comment by hell03610** [comment]
Thanks!! Could you add a separated section in the contributing? If you write in in English that would be perfect, I'm translating the .md files in this repo so it will be easier to merge then.

**Comment by esebastian** [comment]
Hey @andoniaf, would you feel confortable throwing a `docker-compose.yml` in to the mix to make it simpler for people to run the site in development mode (so there's no need to worry about the API or the DB)?

**Comment by andoniaf** [comment]
> Thanks!! Could you add a separated section in the contributing? If you write it in English that would be perfect, I'm translating the .md files in this repo so it will be easier to merge then.

@hell03610 , okey, I will add it as a separated section in English 👍 

> Hey @andoniaf, would you feel confortable throwing a `docker-compose.yml` in to the mix to make it simpler for people to run the site in development mode (so there's no need to worry about the API or the DB)?

Hey @esebastian , I could do it, but how we would like to handle it? I mean, the API is in another repo and as far as I know the API image is not uploaded to any docker registry right? I can create a `docker-compose` explaining that you need to edit it and add your own path to the API folder. Is that okey?

**Comment by esebastian** [comment]
@andoniaf I've uploaded to Docker Hub the [API image](https://cloud.docker.com/u/vlctechhub/repository/docker/vlctechhub/api) built from the current Docker config in its repo [VLCTechHub/VLCTechHub-api](https://github.com/VLCTechHub/VLCTechHub-api).

I'm sure it could be optimized, so feel free to propose there any change you fancy.

**Comment by andoniaf** [comment]
@esebastian I'm working on the `docker-compose`, is there a reason to not copy the Rakefile in the VLCTechHub/VLCTechHub-api image?   If the way to run the api container is with `bundle exec rake up`, to use it "outside" the api repo we need to copy the Rakefile in the image too right?

**Comment by esebastian** [comment]
The rake `up` task is designed to start the server only in the development environment, and the rest of the Rake tasks are not really needed on a production Docker image of the API (apart from the Twitter related ones, but those are still WIP and do not have any impact here).

For the purpose of this issue we shouldn't neither need the API source code nor having the API running in development mode, so it would be enough to use the published production image `vlctechhub/api:latest` without neither any volume mapping nor a custom command override.

Nevertheless, we'll need to provide a value for database connection URL through the `MONGODB_URI` environment variable and we would also need to ensure that the database to use has some useful data, so we'll need to devise a procedure for that, either by seeding the data on the container initialization, by using a database image already containing the data or by any other means.

Does it look good to you or do you think we're missing something?
