### ISSUE TITLE
Sanitize job description when creating a new job

### ISSUE THREAD

**Issue by hell03610** [VLCTechHub/VLCTechHub-site#76]
When adding a new job offer from https://vlctechhub.org/job/new/, chances are the job offer is already published somewhere with some html format. We as users tend to reuse the info with copy/paste instead of writting it directly, so when adding a new offer it will happen often that the text will have some html format. 

However, if the copied text has html format, it wont be sanitized and will be displayed when published, as in https://vlctechhub.org/job/board/5967e407-6030-43ff-9e2b-8f80d4a8fbc6/
![Screenshot from 2019-10-06 16-48-06](https://user-images.githubusercontent.com/581607/66271041-d680a800-e859-11e9-9c71-6f5963c1336c.png)

On the paste event in the job description textarea, we should sanitize the text and remove any html tag, for example the same way it does the github textarea for submitting new issues.

This is very needed in the new job form,  job description textarea, but ideally would also apply to the new job form, job how to apply textarea and in the event form, in the event description textarea.

**Comment by AsterYujano** [comment]
Hello, I am interested to work on this issue :)

May I work on it?

**Comment by AsterYujano** [comment]
Well, I did a correction. I submit my work :)

**Comment by hell03610** [comment]
Sure,go ahead @AsterYujano!
