### ISSUE TITLE
Run linters from yarn scripts instead of github actions

### ISSUE THREAD

**Issue by hell03610** [VLCTechHub/VLCTechHub-site#77]
Ideally also setup travis to run them on pull requests.

**Comment by esebastian** [comment]
This is not necessary. Linters are already triggered from yarn scripts and the Lint workflow is already configured to be triggered on pull requests.

**Comment by esebastian** [comment]
I was wrong regarding the linters being run from yarn scripts, as they're not. It would make sense adding them as yarn scripts to make it easier for people to run them if they're not using any editor extensions to do so.

Nevertheless, those yarn scripts shouldn't be used on the GitHub Actions Lint workflow, at least at for the moment, as right now it would force a full `yarn install` on each run.
