### ISSUE TITLE
When event titles are long, they are hard to read

### ISSUE THREAD

**Issue by hell03610** [VLCTechHub/VLCTechHub-site#84]
See https://vlctechhub.org/events/past/

For example this row:
![Screenshot from 2019-10-11 16-04-50](https://user-images.githubusercontent.com/581607/66658087-0dcbcc00-ec41-11e9-8206-356168ddf41b.png)

The event titles are bigger than the image (that for medium/large screen, image width is 300px), and sometimes are hard to read.

Proposed solution: Make the event title width to be the same as the image, so the "breathing space" for the images are the same for the texts. Check medium and large screens. Some other styles may need to change as for example the horizontal line that is now centered taking into account the empty space might need to be centered without taking it into account.

**Comment by Agreon** [comment]
I would like to help you with that :)

**Comment by hell03610** [comment]
Great!

**Comment by hell03610** [comment]
Shipped! :tada:
