### ISSUE TITLE
Make contact email field required in new job offer form

### ISSUE THREAD

**Issue by esebastian** [VLCTechHub/VLCTechHub-site#89]
On the [new job offer form](https://vlctechhub.org/job/new/), the contact email field (EMAIL DE CONTACTO) is not marked as required, but it is actually required by the API endpoint that receives the form data, so when no contact email is provided the form submission fails.

We would need to make the contact email field required, in the same way the rest of the required fields in the form (PUESTO, DESCRIPCIÓN, PALABRAS CLAVE, SUELDO, CÓMO APLICAR, NOMBRE DE LA EMPRESA, WEB DE LA EMPRESA).

**Comment by myilm** [comment]
i'll take this

**Comment by aman05382** [comment]
I am ready

**Comment by cakhanif** [comment]
#92

**Comment by esebastian** [comment]
Hi @cakhanif, thanks for your contribution but @myilm already took it (see #91).

**Comment by hell03610** [comment]
Shipped! :tada:
