### ISSUE TITLE
Use email input type on the email field of the job submission form

### ISSUE THREAD

**Issue by shakti97** [VLCTechHub/VLCTechHub-site#97]
I think we should validate each field like email should contain a valid email other than any string , company url must be a url etc

**Comment by DavidHernandez** [comment]
Most of the fields are already validated using HTML5 input types. In particular, the e-mail field has no validation. This should be changed. I will need to review the others.

I will update this issue accordingly.

**Comment by lukasleeyo** [comment]
Hello there, I have submitted a pull request regarding this issue. Please verify the changes. Thanks :)
