### ISSUE TITLE
Add loader on publish offer submission

### ISSUE THREAD

**Issue by shakti97** [VLCTechHub/VLCTechHub-site#99]
We need a loader when user clicked the "send the offer" button on publish job offer page until we get some response

**Comment by DavidHernandez** [comment]
@shakti97 this is not needed. The job offers and the event submissions are manually approved. Maybe it is better to just display a message saying this will be approved soon. I will review this with the team to see if it is really needed.

**Comment by shakti97** [comment]
okay no issue
